### ISSUE TITLE
Request To Add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [vintage/party_flutter#32]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). 

On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

If yes, then I request you to add MIT Licence in your repo.

Looking forward to hear from you.

**Comment by vintage** [comment]
Hey @maheshwari-1153 

You already have this project highlighted on yours site - https://startflutter.com/themes/party-app/ Would be great if the screenshots be updated to the latest version, as lots of design changes happened during last time :)
